FORMAT: 1A

# api.datumbox.com

### Resource /1.0/SentimentAnalysis.json [/1.0/SentimentAnalysis.json]

#### SentimentAnalysis [POST]

Identifies the Sentiment of the Document

+ Response 200

### Resource /1.0/TwitterSentimentAnalysis.json [/1.0/TwitterSentimentAnalysis.json]

#### TwitterSentimentAnalysis [POST]

Identifies the Sentiment of Twitter Messages

+ Response 200

### Resource /1.0/SubjectivityAnalysis.json [/1.0/SubjectivityAnalysis.json]

#### SubjectivityAnalysis [POST]

Classifies Document as Subjective or Objective

+ Response 200

### Resource /1.0/TopicClassification.json [/1.0/TopicClassification.json]

#### TopicClassification [POST]

Identifies the Topic of the Document

+ Response 200

### Resource /1.0/SpamDetection.json [/1.0/SpamDetection.json]

#### SpamDetection [POST]

Classifies the Document as spam or nospam

+ Response 200

### Resource /1.0/AdultContentDetection.json [/1.0/AdultContentDetection.json]

#### AdultContentDetection [POST]

Classifies the Document as adult or noadult

+ Response 200

### Resource /1.0/ReadabilityAssessment.json [/1.0/ReadabilityAssessment.json]

#### ReadabilityAssessment [POST]

Evaluates the Readability of the Document

+ Response 200

### Resource /1.0/LanguageDetection.json [/1.0/LanguageDetection.json]

#### LanguageDetection [POST]

Identifies the Language of the Document

+ Response 200

### Resource /1.0/CommercialDetection.json [/1.0/CommercialDetection.json]

#### CommercialDetection [POST]

Classifies the Document as commercial or nocommercial

+ Response 200

### Resource /1.0/EducationalDetection.json [/1.0/EducationalDetection.json]

#### EducationalDetection [POST]

Classifies the Document as educational or noeducational

+ Response 200

### Resource /1.0/GenderDetection.json [/1.0/GenderDetection.json]

#### GenderDetection [POST]

Gender Detection Service

+ Response 200

### Resource /1.0/KeywordExtraction.json [/1.0/KeywordExtraction.json]

#### KeywordExtraction [POST]

Extracts the Keywords of the Document

+ Response 200

### Resource /1.0/TextExtraction.json [/1.0/TextExtraction.json]

#### TextExtraction [POST]

Extracts the clear text from Webpage

+ Response 200

### Resource /1.0/DocumentSimilarity.json [/1.0/DocumentSimilarity.json]

#### DocumentSimilarity [POST]

Estimates the similarity between 2 Documents

+ Response 200

