FORMAT: 1A

# Google Apps Activity API

Provides a historical view of activity.

### Resource /activities [/appsactivity/v1/activities{?drive.ancestorId,drive.fileId,groupingStrategy,pageSize,pageToken,source,userId}]

#### appsactivity.activities.list [GET]

+ Parameters

    + drive.ancestorId
  
    + drive.fileId
  
    + groupingStrategy
  
    + pageSize
  
    + pageToken
  
    + source
  
    + userId

+ Response 200

