FORMAT: 1A

# Google Play Developer API

Lets Android application developers access their Google Play accounts.

### Resource /{packageName}/subscriptions/{subscriptionId}/purchases/{token}/cancel [/{packageName}/subscriptions/{subscriptionId}/purchases/{token}/cancel]

#### androidpublisher.purchases.cancel [POST]

+ Parameters

    + packageName (required)
  
    + subscriptionId (required)
  
    + token (required)

+ Response 200

### Resource /{packageName}/subscriptions/{subscriptionId}/purchases/{token} [/{packageName}/subscriptions/{subscriptionId}/purchases/{token}]

#### androidpublisher.purchases.get [GET]

+ Parameters

    + packageName (required)
  
    + subscriptionId (required)
  
    + token (required)

+ Response 200

