FORMAT: 1A

# Google Fonts Developer API

The Google Fonts Developer API.

### Resource /webfonts [/webfonts/v1/webfonts{?sort}]

#### webfonts.webfonts.list [GET]

+ Parameters

    + sort

+ Response 200

