FORMAT: 1A

# Translate API

Lets you translate text from one language to another

### Resource /v2/detect [/language/translate/v2/detect{?q}]

#### language.detections.list [GET]

+ Parameters

    + q (required)

+ Response 200

### Resource /v2/languages [/language/translate/v2/languages{?target}]

#### language.languages.list [GET]

+ Parameters

    + target

+ Response 200

### Resource /v2 [/language/translate/v2{?q,target,cid,format,source}]

#### language.translations.list [GET]

+ Parameters

    + q (required)
  
    + target (required)
  
    + cid
  
    + format
  
    + source

+ Response 200

