FORMAT: 1A

# PageSpeed Insights API

Lets you analyze the performance of a web page and get tailored suggestions to make that page faster.

### Resource /runPagespeed [/pagespeedonline/v1/runPagespeed{?url,filter_third_party_resources,locale,rule,screenshot,strategy}]

#### pagespeedonline.pagespeedapi.runpagespeed [GET]

+ Parameters

    + url (required)
  
    + filter_third_party_resources
  
    + locale
  
    + rule
  
    + screenshot
  
    + strategy

+ Response 200

