FORMAT: 1A

# Groups Migration API

Groups Migration Api.

### Resource /{groupId}/archive [/{groupId}/archive]

#### groupsmigration.archive.insert [POST]

+ Parameters

    + groupId (required)

+ Response 200

