FORMAT: 1A

# GetIt REST API

This is the V.1.0.0 for GetIt REST API

### Resource /catalog/info [/catalog/info]

#### info [POST]

Return an array of matching elements by text

+ Response 200

### Resource /catalog/infobyids [/catalog/infobyids]

#### infobyids [POST]

Return an array of matching elements by id

+ Response 200

### Resource /catalog/dependencyinfo [/catalog/dependencyinfo]

#### infobyids [POST]

Return dependencies Ids separated by ';'

+ Response 200

