FORMAT: 1A

# Freebase Search

Find Freebase entities using textual queries and other constraints.

### Resource /reconcile [/freebase/v1-sandbox/reconcile{?confidence,kind,lang,limit,name,prop}]

#### freebase.reconcile [GET]

+ Parameters

    + confidence
  
    + kind
  
    + lang
  
    + limit
  
    + name
  
    + prop

+ Response 200

### Resource /search [/freebase/v1-sandbox/search{?as_of_time,callback,cursor,domain,encode,exact,filter,format,help,indent,lang,limit,mid,mql_output,output,prefixed,query,scoring,spell,stemmed,type,with,without}]

#### freebase.search [GET]

+ Parameters

    + as_of_time
  
    + callback
  
    + cursor
  
    + domain
  
    + encode
  
    + exact
  
    + filter
  
    + format
  
    + help
  
    + indent
  
    + lang
  
    + limit
  
    + mid
  
    + mql_output
  
    + output
  
    + prefixed
  
    + query
  
    + scoring
  
    + spell
  
    + stemmed
  
    + type
  
    + with
  
    + without

+ Response 200

