FORMAT: 1A

# CustomSearch API

Lets you search over a website or collection of websites

### Resource /v1 [/customsearch/v1{?q,c2coff,cr,cref,cx,dateRestrict,exactTerms,excludeTerms,fileType,filter,gl,googlehost,highRange,hl,hq,imgColorType,imgDominantColor,imgSize,imgType,linkSite,lowRange,lr,num,orTerms,relatedSite,rights,safe,searchType,siteSearch,siteSearchFilter,sort,start}]

#### search.cse.list [GET]

+ Parameters

    + q (required)
  
    + c2coff
  
    + cr
  
    + cref
  
    + cx
  
    + dateRestrict
  
    + exactTerms
  
    + excludeTerms
  
    + fileType
  
    + filter
  
    + gl
  
    + googlehost
  
    + highRange
  
    + hl
  
    + hq
  
    + imgColorType
  
    + imgDominantColor
  
    + imgSize
  
    + imgType
  
    + linkSite
  
    + lowRange
  
    + lr
  
    + num
  
    + orTerms
  
    + relatedSite
  
    + rights
  
    + safe
  
    + searchType
  
    + siteSearch
  
    + siteSearchFilter
  
    + sort
  
    + start

+ Response 200

